baseURL = 'http://example.org/'
languageCode = 'zh-TW'
title = 'This is demo site'
theme = 'Loveit'

# 作者配置
[author]
  name = "Demo"
  email = ""
  link = ""

# 设置默认的语言 ["en", "zh-cn", "fr", "pl", ...]
defaultContentLanguage = "zh-tw"

[languages]
  [languages.zh-tw]
    weight = 1
    title = "展示"
    languageCode = "zh-TW"
    languageName = "繁體中文"
    hasCJKLanguage = true
    [[languages.zh-tw.menu.main]]
      weight = 1
      identifier = "demo1"
      pre = ""
      post = ""
      name = "展示1"
      url = "/demo1/"
      title = ""
    [[languages.zh-tw.menu.main]]
      weight = 2
      identifier = "demo2"
      pre = ""
      post = ""
      name = "展示2"
      url = "/demo2/"
      title = ""
    [[languages.zh-tw.menu.main]]
      weight = 3
      identifier = "demo3"
      pre = ""
      post = ""
      name = "展示3"
      url = "/demo3/"
      title = ""

  [languages.en]
    weight = 2
    title = "Demo"
    languageCode = "en"
    languageName = "English"
    [[languages.en.menu.main]]
      weight = 1
      identifier = "demo1"
      pre = ""
      post = ""
      name = "Demo1"
      url = "/demo1/"
      title = ""
    [[languages.en.menu.main]]
      weight = 2
      identifier = "demo2"
      pre = ""
      post = ""
      name = "Demo2"
      url = "/demo2/"
      title = ""
    [[languages.en.menu.main]]
      weight = 3
      identifier = "demo3"
      pre = ""
      post = ""
      name = "Demo3"
      url = "/demo3/"
      title = ""




